[auth]
redirect_uri = "https://canned-info-builder.streamlit.app/oauth2callback"
cookie_secret = "your-random-32-char-string"
client_id = "5148...apps.googleusercontent.com"
client_secret = "GOCSPX-..."
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
